version: "3.7"
services:
    teslaris:
        container_name: "teslaris-api"
        build:
            context: .
            dockerfile: .docker/Dockerfile
        depends_on:
            - db
        environment:
            - API_PORT=8081
            - DB_USERNAME=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - DB_PORT=5432
        ports:
            - "8081:8081"
        networks:
            - teslaris-network
    db:
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=TeslaRISDB
            - APP_DB_USER=docker
            - APP_DB_PASS=docker
            - APP_DB_NAME=TeslaRISDB
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data
            - ./db:/docker-entrypoint-initdb.d/
        networks:
            - teslaris-network

networks:
    teslaris-network:
        name: teslaris-network

volumes:
    db: