name: Java CI with Maven

on:
    push:
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:13.3
                env:
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_USER: postgres
                    POSTGRES_DB: TeslaRISDB
                ports:
                    - 5432:5432
            elasticsearch:
                image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
                env:
                    discovery.type: single-node
                    ES_JAVA_OPTS: -Xms1g -Xmx1g
                    xpack.security.enabled: false
                ports:
                    - 9200:9200

        steps:
            - uses: actions/checkout@v3
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                  java-version: "11"
                  distribution: "temurin"
                  cache: maven
            - name: Start Docker Compose
              run: docker-compose up -ds
            - name: Build with Maven
              run: mvn -B package --file pom.xml
              env:
                  DB_PASSWORD: postgres
            - name: Run Tests
              run: mvn test
              env:
                  DB_PASSWORD: postgres
            - name: Run Tests with Code Coverage
              run: mvn clean verify jacoco:report
              env:
                  DB_PASSWORD: postgres
            # - name: Upload Code Coverage Report
            #   uses: actions/upload-artifact@v2
            #   with:
            #       name: coverage-report
            #       path: target/site/jacoco/index.html
            - name: Stop Docker Compose
              run: docker-compose down
            - name: Generate Checkstyle Report
              run: mvn checkstyle:checkstyle
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
